# Generated by Django 3.2.13 on 2023-08-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connect4game",
            name="winner",
        ),
        migrations.AddField(
            model_name="connect4game",
            name="game_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="connect4game",
            name="message",
            field=models.CharField(default="", max_length=100),
        ),
    ]
